python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-1.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-2.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-3.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-1.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-2.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-3.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-1.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-2.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/sin_environment_settings-3.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-1.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-2.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-3.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-4.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-1.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-2.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-3.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-4.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-1.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-2.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-3.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM3_environment_settings-4.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-1.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-2.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-3.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-4.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-1.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-2.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-3.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-4.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-1.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-2.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-3.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/FM4_environment_settings-4.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-1.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-2.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-3.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-4.json --AGENT_TYPE A2C --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-1.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-2.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-3.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-4.json --AGENT_TYPE PPO --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-1.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-2.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-3.json --AGENT_TYPE DQN --UBUNTU True
python3 train.py --ENVIRONMENT_SETTINGS ./batch_training/granular_environment_settings-4.json --AGENT_TYPE DQN --UBUNTU True
